#Logging
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
  #        type:
  #          descriptor:
  #            sql:
  #              BasicBinder: TRACE
  file:
    name: ./logs/mngr-srv.log

#Server
server:
  port: 8080

#Spring
spring:
  application:
    name: mngr-srv
  profiles:
    active: development
  #Misc
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always

---

#Development config
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:postgresql://localhost:5432/mosmngr
    username: mosmngr
    password: mosmngr
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
  #Security
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/auth/realms/mosm/protocol/openid-connect/certs

---

#Production config
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://app-db:5432/mosmngr
    username: mosmngr
    password: mosmngr
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
  #Security
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/mosm/protocol/openid-connect/certs